apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-latest   # must match the label in your deployment
  ports:
    - protocol: TCP
      port: 80            # Port for the user (like Locust or browser)
      targetPort: 8000    # Port your FastAPI app listens on
  type: NodePort          # Exposes the service on a port on each node